### ISSUE TITLE
License and Copyright notes

### ISSUE THREAD

**Issue by rchavik** [hurad/hurad#26]
Hello,

I've noticed that some files are copied from Croogo CMS that I help maintain.  You're of course very much welcome to use these files, but please do not remove copyright and licensing information headers from these files.

**Comment by atkrad** [comment]
Hello @rchavik 
I want to add copyright and licensing information in headers before first stable release.
Thank you for your notification.

**Comment by rchavik** [comment]
Why close the issue then?

Please reopen and **only close the issue** when the proper copyright notices have been restored in the offending files. So far I have noticed:

[Lib/Hurad.php](https://github.com/hurad/hurad/blob/master/Lib/Hurad.php) copied from [Lib/Croogo.php](https://github.com/croogo/croogo/blob/f441303ce/Lib/Croogo.php)
[Lib/HrPlugin.php](https://github.com/hurad/hurad/blob/master/Lib/HrPlugin.php) copied from [Plugin/Extensions/Lib/CroogoPlugin.php](https://github.com/croogo/croogo/blob/f441303ce/Plugin/Extensions/Lib/CroogoPlugin.php)
[Lib/HrTheme.php](https://github.com/hurad/hurad/blob/master/Lib/HrTheme.php) copied from [Plugin/Extensions/Lib/CroogoTheme.php](https://github.com/croogo/croogo/blob/f441303ce/Plugin/Extensions/Lib/CroogoTheme.php)
[Lib/HrNav.php](https://github.com/hurad/hurad/blob/master/Lib/HrNav.php) copied from [Lib/CroogoNav.php](https://github.com/croogo/croogo/blob/f441303ce/Lib/CroogoNav.php)
[Plugin/Tinymce/View/Helper/TinymceHelper.php](https://github.com/hurad/hurad/blob/master/Plugin/Tinymce/View/Helper/TinymceHelper.php) copied from [Plugin/Tinymce/View/Helper/TinymceHelper.php](https://github.com/croogo/croogo/blob/f441303ce/Plugin/Tinymce/View/Helper/TinymceHelper.php)

Some other bits and pieces are also copied in bootstrap files etc.

Further, there are likely to be more files copied from other authors as well.  I see @predominant's Gravatar helper there with copyrights removed too.

This is uncool.

**Comment by atkrad** [comment]
I restored all the copyright notices.
If there is problem please tell me.

Thanks

**Comment by rchavik** [comment]
I took a brief look, seem you have added back the authors line which is nice.

Though I'm not sure how to handle the `@license` info in the header.  Some files originally already have the `@license`, some don't.

Croogo itself is MIT licensed, and Hurad seems to adopt GPL.  However, I don't think you can 'relicense' these files as GPL. Perhaps retain all the original headers in each file (I see some project keeps a separate file listing which license a given file is using).

Let's keep this issue open while we research the issue.

Thanks.

**Comment by predominant** [comment]
Licence, Copyright, Author, basically all header information should be retained as the original file. If you need to add more information, add a second header block below it, adding your own information.

You cannot re-license or remove information like that.

**Comment by fahad19** [comment]
as far as I am aware, dual-licensing is possible (MIT/GPL together). but of course, like @predominant said, all header information should remain untouched from the original file.

**Comment by dogmatic69** [comment]
![](http://i.imgur.com/iST1H89.png)

**Comment by predominant** [comment]
:+1:

**Comment by atkrad** [comment]
I changed all the copyright information.
If there is problem please tell me.

Thanks

**Comment by rchavik** [comment]
Thank you.

I see that you've kept the original headers.   I'm not sure whether re-licensing these files are 'allowed' though, googling shows conflicting result.  I'll research more.

Can you also add the headers for:

[Event/HrEventManager.php](https://github.com/hurad/hurad/blob/master/Event/HrEventManager.php) -> [Event/CroogoEventManager.php](https://github.com/croogo/croogo/blob/f441303ce/Event/CroogoEventManager.php)

**Comment by atkrad** [comment]
I added the headers for [HrEventManager.php](https://github.com/hurad/hurad/blob/master/Event/HrEventManager.php)
What is the the result of your researching?

Thanks for your helping.

**Comment by zoghal** [comment]
خسته نباشی عزیز. دنبال ایونت ها بودی برای این بود.!!!! همون روز تو فروم ردت رو تا اینجا گرفتم. چون سوالت خیلی برام تابلو بود. خواستم اخطار بدم دیدم به من مربوط نیست.ولی الان کمی دخالت می کنم. چون اولا راهش این نیست، اونم اینجا تو گیت هاب.دوم این مسائل برای خیلی از ما برنامه نویس های ایرانی تو گیت بد تموم میشه. خودتون بهتر می دونید.

پیشنهاد میدم. یک عذر خواهی کنید. پروژه رو مجدد فورک بگیر و خود کروگو رو توسعه بدید  برای زبان فارسی. یا ایرانی بازی می خوای در بیارید. ببرید یک جایی که پریویت باشه. 
می بینید که حتی به تغییر نام یک کلاس هم حساس هستند.و در اصل هم شما حق حذف یا تغییر کلی رو ندارید. فقط میتونید اضافه کنید. 
ممنون. باز عذر می خوام قصد جسارت نداشتم.

**Comment by atkrad** [comment]
سلام آقای سوزنچی
فقط بابت اطلاع عرض کنم که من تمامی فایل هایی را که با آن مشکل داشتند را پاک کردم و از نو خودم نوشتم (به غیر از یک مورد که اون هم حتما تغییر میکنه.

**Comment by dogmatic69** [comment]
Google translate for the lazy:

@zoghal 

> You're not tired. Ionut you are looking for this.!! The same day I got here to the class forum. Because your question, so I was painting. I notice I do not concern me., But I am a bit involved. This is the first way, he is here in the hub gate. Secondly, we have a lot of problems for Iranian programmer you dies bad gates. You know yourself better.
> 
> I suggested. If an apology. Fork this project on hold and give Krvgv of the Persian language. Iranian imperative to get the game going on. Take a right where Pryvyt.
> You can see that they are sensitive even to rename a class., And in fact you do not have a general right to delete or change. You can only add.
> Thank you. Again I had the courage to forgive.

@atkrad 

> Hi Mr. switchman
> Just because I know I have to delete all the files that had problems with it and I re-wrote myself (except the one that he's sure to change.

**Comment by zoghal** [comment]
@dogmatic69 
Dear Carl , this is basically covers what we said..
I was tracking atkrad for a while and he was asking some question on Persian forum(cakephp.ir) as well but he didn't mentioned that what he wanted the events for, and finally I found him here..
Now I just said to him that by doing these kind of things on Github makes all Iranians to look bad and people gonna think we are all doing that in this industry! and I am not very happy about that!
Following that, I suggested that would be good if you "atkrad" apologise and fork the project and then extend the project in Persian language! Also I suggested that it is not common to change the name of the class or project and you should either add or change a class.

Finally I said I don't want make you feel bad just wanted to say this is not the correct way and makes Iranians face bad! that's it!

And he replied that, just to let you know I've deleted all files that they had problem with and I've written all by myself excluding one file which is gonna change soon.

**Comment by rchavik** [comment]
@zoghal 

I noted in the original issue that we are fine with re-use these files and it's unfortunate that @atkrad decides to delete those files.

I think the main issue is that some credits/copyrights header was removed. Those have been restored back, so I think that particular matter is resolved.

In terms of renaming files and class names, personally I think it's fine as long as the copyrights headers/licensing information is kept.

I think only the re-licensing of files is in question.  I think you can have projects containing both MIT and GPL sources, but whether it's allowed to change a file's original license from MIT to GPL is unclear to me:
- http://stackoverflow.com/questions/4035702/can-i-relicense-someones-mit-code-under-gpl
- http://askubuntu.com/questions/46380/how-do-i-use-gpl-and-mit-licenses-correctly
- http://programmers.stackexchange.com/questions/105912/can-you-change-code-distributed-under-the-mit-license-and-re-distribute-it-unde
- http://stackoverflow.com/questions/706799/meaning-of-mit-license
