### ISSUE TITLE
Plugin Interop

### ISSUE THREAD

**Issue by rchavik** [hurad/hurad#27]
I'm not sure how different your plan with Hurad, but it might be worth to pursue third party plugin interoperability between Croogo <-> Hurad.

**Comment by atkrad** [comment]
I want to make blogging system like WordPress, ...
How to make this cooperation?

Thanks

**Comment by rchavik** [comment]
In croogo, the plugins are 'integrated' via several mechanisms:
- activation class
- hooks: for adminMenus, rowActions, adminTabs, adminBlocks
- filters (via events)
- events

If you could maintain compatibility with croogo at some level, hurad would be able to leverage existing croogo plugins if desired.

**Comment by atkrad** [comment]
There is no problem for cooperation with Croogo.
But i don't know how should I start?
