### ISSUE TITLE
installer bug

### ISSUE THREAD

**Issue by atabrizian** [hurad/hurad#67]
I had hurad installed perviously but when I pulled changes from repo it just shows the installer page and no else page.

**Comment by atkrad** [comment]
@ghost098 All tables are available?
Please reinstall Hurad.

**Comment by atabrizian** [comment]
yes, they are. (Please resolve it yourself.)

**Comment by atkrad** [comment]
@ghost098 It works for me.
I'll check again

**Comment by atabrizian** [comment]
@atkrad I don't no why, but my database.php contents where replaced with default values!
